In [1]:
import numpy as np

In [2]:
#Question 1
#Create a 1-d array of random integer numbers of size 10.

In [3]:
ran_arr = np.random.randint(0,10,10)
print("The random array in given range is:",ran_arr)

The random array in given range is: [0 4 5 5 7 9 1 8 1 5]


In [4]:
#Question 2
#Convert the above 1-D array to a 2-D array.

In [5]:
two_d = ran_arr.reshape(2,5)
print("The 2D array of above array is",two_d)

The 2D array of above array is [[0 4 5 5 7]
 [9 1 8 1 5]]


In [6]:
#Question 3
#Try to iterate the arry using nditer().

In [7]:
for i in np.nditer(ran_arr):
    print(i)

0
4
5
5
7
9
1
8
1
5


In [8]:
#Question 4
#Make two 1-D array using arange(), concatenate the two arrays both, row wise and
#column wise.

In [9]:
arr1 = np.arange(1,5).reshape(2,2)
print('First array is:',arr1)
arr2 = np.arange(5,9).reshape(2,2)
print('Second array is:',arr2)

arr_r = np.append(arr1,arr2,axis=0)
print('ROW wise concatenation is:',arr_r)
arr_c = np.append(arr1,arr2,axis=1)
print('Column wise concatenation is:',arr_c)

First array is: [[1 2]
 [3 4]]
Second array is: [[5 6]
 [7 8]]
ROW wise concatenation is: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Column wise concatenation is: [[1 2 5 6]
 [3 4 7 8]]


In [10]:
#Question 5
#Apply stack() to join two arrays.

In [11]:
arr1 = np.arange(4)
arr2 = np.arange(4)

arr = np.stack((arr1,arr2),axis=0)
print("The array after using stack() is:",arr)

The array after using stack() is: [[0 1 2 3]
 [0 1 2 3]]


In [12]:
#Question 6
#Use where() to find an array element.

In [16]:
arr = np.arange(5)
print("The array is:",arr)

n = int(input("Enter the element to be find:"))
A = np.where(arr == n)

print("Element is:",A)

The array is: [0 1 2 3 4]
Enter the element to be find:2
Element is: (array([2], dtype=int64),)


In [14]:
#Question 7
#Try searchsorted() function in arrays. Specify what is the use of this function?

In [15]:
arr = [1,2,3,4,5]
print("Initial Sorted Array is:",arr)

n=int(input("Enter the element to insert:"))
ss = np.searchsorted(arr,n)
print("Indices to maintain sorted array is:",ss)

Initial Sorted Array is: [1, 2, 3, 4, 5]
Enter the element to insert:3
Indices to maintain sorted array is: 2
